sunfish-shogi/shogihome

- src/background.ts
- src/ipc/background.ts
https://github.com/sunfish-shogi/electron-shogi/issues/6
> Fix for mac

- src/components/dialog/AppSettingDialog.vue
- src/settings/app.ts
- src/settings/fs.ts
- src/store/index.ts
https://github.com/sunfish-shogi/electron-shogi/issues/34
> return code detection and setting

- src/components/primitive/RecordView.vue
- src/shogi/board.ts
- src/shogi/position.ts
- src/shogi/record.ts
- src/store/action.ts
- src/store/index.ts
- src/store/mutation.ts
- tests/unit/shogi/record.spec.ts
https://github.com/sunfish-shogi/electron-shogi/issues/11
> detect repetition

- src/components/dialog/USIEngineManagementDialog.vue
- src/css/dialog.css
- src/settings/usi.ts
- tests/unit/settings/usi.spec.ts
https://github.com/sunfish-shogi/electron-shogi/issues/63
> Add "duplicate" button

- src/components/tab/EngineAnalyticsElement.vue
https://github.com/sunfish-shogi/electron-shogi/issues/55
> highlight best move on multi-PV

- src/components/primitive/RecordView.vue
https://github.com/sunfish-shogi/electron-shogi/issues/68
> display move comments in RecordView #68

- src/components/main/BoardPane.vue
- src/ipc/background/menu.ts
- src/ipc/menu.ts
- src/ipc/renderer.ts
- src/shogi/board.ts
- src/shogi/position.ts
- tests/unit/shogi/position.spec.ts
https://github.com/sunfish-shogi/electron-shogi/issues/79
> pull-down list for initializing position #79

- src/helpers/datetime.ts
- src/settings/game.ts
- src/store/index.ts
> insert game information to record metadata

- src/store/record.ts
https://github.com/sunfish-shogi/electron-shogi/issues/85
> fix bug of evaluation chart

- src/helpers/string.ts
- src/shogi/kakinoki.ts
- src/shogi/record.ts
- src/store/index.ts
- tests/unit/shogi/kakinoki.spec.ts
- tests/unit/shogi/record.spec.ts
https://github.com/sunfish-shogi/electron-shogi/issues/101
> Fix Record.clear() function

- src/components/dialog/BussyMessage.vue
- src/components/dialog/ConfirmDialog.vue
- src/components/dialog/ErrorMessage.vue
- src/components/dialog/GameDialog.vue
- src/components/dialog/InfoMessage.vue
- src/components/main/BoardPane.vue
- src/components/main/TabPane.vue
- src/components/primitive/BoardLayout.ts
- src/components/primitive/BoardView.vue
- src/components/primitive/RecordView.vue
https://github.com/sunfish-shogi/electron-shogi/issues/103
> Fix for Volar #103

- src/components/main/BoardPane.vue
`局面の初期化` の Select 要素に対してスタイルが適用されていなかったのを修正。
> fix style of select element

- src/store/analysis.ts
https://github.com/sunfish-shogi/electron-shogi/issues/113
> fix move comparision in analysis #113

- src/store/game.ts
- src/store/index.ts
https://github.com/sunfish-shogi/electron-shogi/issues/120
> fix game initialization bug #120

- src/components/tab/RecordInfo.vue
- ファイルパスを表示 https://github.com/sunfish-shogi/electron-shogi/issues/130
- Ctrl+C, Ctrl+V が奪われないように改善
> Update RecordInfo tab

- public/icon/close_FILL0_wght400_GRAD0_opsz48.svg
- public/icon/play_arrow_FILL1_wght400_GRAD0_opsz48.svg
- src/assets/icons.ts
- src/components/dialog/PVPreviewDialog.vue
- src/components/primitive/BoardView.vue
- src/components/tab/EngineAnalyticsElement.vue
- src/store/usi.ts
https://github.com/sunfish-shogi/electron-shogi/issues/138
> Add PV preview dialog

- src/store/usi.ts
https://github.com/sunfish-shogi/electron-shogi/issues/144
> fix USIMonitor

- src/components/tab/EngineAnalyticsElement.vue
- src/store/usi.ts
https://github.com/sunfish-shogi/electron-shogi/issues/145
> Add "nodes" column

- src/components/tab/EngineAnalyticsElement.vue
- src/ipc/api.ts
- src/ipc/background/index.ts
- src/ipc/background/usi/engine.ts
- src/ipc/background/usi/index.ts
- src/ipc/channel.ts
- src/ipc/preload.ts
- src/ipc/setup.ts
- src/ipc/web.ts
- src/players/human.ts
- src/players/player.ts
- src/players/usi.ts
- src/settings/usi.ts
- src/shogi/record.ts
- src/store/game.ts
- src/store/index.ts
- src/store/usi.ts
- tests/unit/store/game.spec.ts
https://github.com/sunfish-shogi/electron-shogi/issues/5
> USI Ponder

- src/components/dialog/USIEngineOptionDialog.vue
- src/ipc/background/usi/engine.ts
- src/ipc/background/usi/index.ts
https://github.com/sunfish-shogi/electron-shogi/issues/148
> Enhance engine process management

- src/shogi/position.ts
- tests/unit/shogi/position.spec.ts
https://github.com/sunfish-shogi/electron-shogi/issues/152
> fix isPawnDropMate bug

- src/components/dialog/AppSettingDialog.vue
- src/css/color.css
- src/settings/app.ts
https://github.com/sunfish-shogi/electron-shogi/issues/105
> add cherry blossom thema

- src/components/dialog/GameDialog.vue
- src/components/dialog/USIEngineOptionDialog.vue
- src/css/color.css
https://github.com/sunfish-shogi/electron-shogi/issues/150
> Add setting button into GameDialog

- src/components/dialog/AnalysisDialog.vue
- src/components/dialog/GameDialog.vue
- src/components/dialog/PlayerSelector.vue
- src/components/dialog/ResearchDialog.vue
- src/settings/usi.ts
プレイヤー選択の UI を共通のコンポーネントに切り出して、機能を充実させます。
> Add PlayerSelector component

- src/components/primitive/RecordView.vue
> Fix RecordView style

- src/components/dialog/GameDialog.vue
- src/components/dialog/PlayerSelector.vue
- src/components/dialog/USIEngineManagementDialog.vue
- src/settings/usi.ts
- tests/unit/settings/usi.spec.ts
https://github.com/sunfish-shogi/electron-shogi/issues/176
> fix: check whether the engine is removed

- src/ipc/background/help.ts
- src/ipc/background/menu.ts
https://github.com/sunfish-shogi/electron-shogi/issues/91
> Add help menu

- src/shogi/csa.ts
- src/shogi/record.ts
- src/store/analysis.ts
- src/store/index.ts
- src/store/record.ts
- tests/unit/shogi/csa.spec.ts
- tests/unit/shogi/kakinoki.spec.ts
- tests/unit/shogi/record.spec.ts
- tests/unit/store/index.spec.ts
https://github.com/sunfish-shogi/electron-shogi/issues/161
> extended comment of CSA file format

- src/components/menu/FileMenu.vue
- src/components/menu/InitialPositionMenu.vue
- src/css/color.css
- src/css/dialog.css
メニューにおける「戻る」ボタンが他のボタンと区別しやすいよう、背景色を赤に変更する。
> Change close button color

- src/components/tab/EngineAnalyticsElement.vue
https://github.com/sunfish-shogi/electron-shogi/issues/193
> Fix pv hilight

- src/store/index.ts
- src/store/usi.ts
https://github.com/sunfish-shogi/electron-shogi/issues/198
> Fix to clear usi info at game start

- src/components/tab/EvaluationChart.vue
- src/helpers/testing.ts
- src/ipc/usi.ts
- src/players/builder.ts
- src/players/player.ts
- src/players/usi.ts
- src/shogi/record.ts
- src/store/analysis.ts
- src/store/csa.ts
- src/store/game.ts
- src/store/index.ts
- src/store/record.ts
- src/store/usi.ts
- tests/unit/mock/player.ts
- tests/unit/store/csa.spec.ts
- tests/unit/store/game.spec.ts
- tests/unit/store/index.spec.ts
- 棋譜ファイルを読み込んだときの手番の取り扱いが間違ってたので修正する。（ https://github.com/sunfish-shogi/electron-shogi/issues/202 への修正）
- エンジンが高頻度で評価値を更新すると描画が重くなる問題への修正。
- 探索結果の取り扱いについて設計を見直す。
> Fix and refactor evaluation chart

- src/components/dialog/AppSettingDialog.vue
- src/components/dialog/CSAGameDialog.vue
- src/components/dialog/GameDialog.vue
- src/helpers/path.ts
- src/ipc/api.ts
- src/ipc/background/index.ts
- src/ipc/background/menu.ts
- src/ipc/background/settings.ts
- src/ipc/channel.ts
- src/ipc/preload.ts
- src/ipc/web.ts
- src/settings/app.ts
- src/settings/csa.ts
- src/settings/game.ts
- src/store/csa.ts
- src/store/game.ts
- src/store/index.ts
- tests/unit/mock/csa.ts
- tests/unit/mock/game.ts
- tests/unit/settings/csa.spec.ts
- tests/unit/store/csa.spec.ts
- tests/unit/store/game.spec.ts
https://github.com/sunfish-shogi/electron-shogi/issues/9
> Add auto-save feature

- src/components/dialog/BussyMessage.vue
- src/components/dialog/CSAGameDialog.vue
- src/components/dialog/CSAGameReadyDialog.vue
- src/components/dialog/ConfirmDialog.vue
- src/components/dialog/ErrorMessage.vue
- src/components/dialog/GameDialog.vue
- src/components/dialog/InfoMessage.vue
- src/css/dialog.css
- src/helpers/path.ts
- src/helpers/string.ts
- src/ipc/background/csa/client.ts
- src/ipc/web.ts
- src/settings/csa.ts
- src/settings/game.ts
- src/shogi/record.ts
- src/store/csa.ts
- src/store/game.ts
- src/store/index.ts
- src/store/message.ts
- tests/unit/mock/csa.ts
- tests/unit/mock/game.ts
- tests/unit/settings/csa.spec.ts
- tests/unit/store/csa.spec.ts
- tests/unit/store/game.spec.ts
- tests/unit/store/index.spec.ts
https://github.com/sunfish-shogi/electron-shogi/issues/10
> Add repeat feature

- tests/unit/store/index.spec.ts
https://github.com/sunfish-shogi/electron-shogi/pull/233#issuecomment-1277023941
npm update をするとテストが通らなくなる。
navigator へモック関数を挿入するコードを修正する。
> fix test code

- package-lock.json
- package.json
This sets to use new version `electron-builder` for `vue-cli-plugin-electron-builder` then solves the issue https://github.com/sunfish-shogi/electron-shogi/issues/232.
> Force to use new version

- src/components/dialog/AppSettingDialog.vue
- src/components/dialog/USIEngineManagementDialog.vue
- src/components/dialog/USIEngineOptionDialog.vue
- src/ipc/api.ts
- src/ipc/background/index.ts
- src/ipc/background/usi/index.ts
- src/ipc/preload.ts
- src/players/builder.ts
- src/players/usi.ts
- src/settings/app.ts
- src/store/analysis.ts
- src/store/csa.ts
- src/store/game.ts
- src/store/index.ts
- tests/unit/players/builder.spec.ts
- tests/unit/players/usi.spec.ts
- tests/unit/store/csa.spec.ts
- tests/unit/store/game.spec.ts
https://github.com/sunfish-shogi/electron-shogi/issues/248
> Add engine timeout seconds setting

- src/components/dialog/CSAGameDialog.vue
- src/ipc/api.ts
- src/ipc/background/csa/client.ts
- src/ipc/background/csa/index.ts
- src/ipc/background/index.ts
- src/ipc/preload.ts
- src/settings/csa.ts
- src/store/csa.ts
- tests/unit/ipc/background/csa/client.spec.ts
- tests/unit/mock/csa.ts
- tests/unit/settings/csa.spec.ts
- tests/unit/store/csa.spec.ts
https://github.com/sunfish-shogi/electron-shogi/issues/204
> send score and PV to CSA server

- src/components/dialog/AnalysisDialog.vue
- src/components/dialog/AppSettingDialog.vue
- src/components/dialog/CSAGameDialog.vue
- src/components/dialog/CSAGameReadyDialog.vue
- src/components/dialog/ConfirmDialog.vue
- src/components/dialog/ErrorMessage.vue
- src/components/dialog/GameDialog.vue
- src/components/dialog/InfoMessage.vue
- src/components/dialog/PVPreviewDialog.vue
- src/components/dialog/PasteDialog.vue
- src/components/dialog/ResearchDialog.vue
- src/components/dialog/USIEngineManagementDialog.vue
- src/components/dialog/USIEngineOptionDialog.vue
- src/components/main/BoardPane.vue
- src/ipc/background/menu.ts
- src/store/index.ts
https://github.com/sunfish-shogi/electron-shogi/issues/260
> ホットキー（ショートカットキー）の強化

- src/components/dialog/PVPreviewDialog.vue
- src/components/tab/EngineAnalyticsElement.vue
読み筋の再現ダイアログで、現在の指し手のテキストをハイライトします。
> PV move highlighting

- .github/workflows/release.yml
- package.json
- scripts/archive.mjs
https://github.com/sunfish-shogi/electron-shogi/issues/272
> linux release setting

- src/store/csa.ts
- src/store/game.ts
- src/tests/store/csa.spec.ts
- src/tests/store/game.spec.ts
https://github.com/sunfish-shogi/electron-shogi/issues/306
> fix error handling of onSaveRecord

- src/components/dialog/CSAGameDialog.vue
- src/settings/csa.ts
- src/store/csa.ts
- src/tests/mock/csa.ts
- src/tests/settings/csa.spec.ts
https://github.com/sunfish-shogi/electron-shogi/issues/254
> Add auto relogin feature

- src/ipc/background/csa/client.ts
Floodgate は LOGOUT コマンドに対応していないらしいので、いきなり接続を切るように修正する。
なお v1.3.0 時点では実装漏れによって結果的に LOGOUT を送らずに切断する動作になっていた。
> fix for Floodgate

- src/components/primitive/RecordView.vue
https://github.com/sunfish-shogi/electron-shogi/issues/317
> Fix RecordView layout

- src/store/index.ts
workaround for https://github.com/sunfish-shogi/electron-shogi/issues/316
> fix onGameEnd #316

- src/background/settings.ts
- src/common/settings/analysis.ts
- src/common/settings/app.ts
- src/common/settings/csa.ts
- src/common/settings/game.ts
- src/common/settings/player.ts
- src/common/settings/research.ts
- src/common/settings/usi.ts
- src/common/settings/window.ts
- src/tests/common/settings/analysis.spec.ts
- src/tests/common/settings/app.spec.ts
- src/tests/common/settings/csa.spec.ts
- src/tests/common/settings/game.spec.ts
- src/tests/common/settings/research.spec.ts
- src/tests/common/settings/window.spec.ts
https://github.com/sunfish-shogi/electron-shogi/issues/199
> enhance setting file loader #199

- src/common/settings/app.ts
- src/renderer/store/index.ts
- src/renderer/view/dialog/AppSettingDialog.vue
- src/renderer/view/main/StandardLayout.vue
- src/renderer/view/main/TabPane.vue
- src/tests/common/settings/app.spec.ts
- src/tests/renderer/store/index.spec.ts
https://github.com/sunfish-shogi/electron-shogi/issues/264
> Add comment layout setting #264

- src/common/settings/app.ts
- src/renderer/css/control.css
- src/renderer/view/dialog/AppSettingDialog.vue
- src/renderer/view/dialog/ErrorMessage.vue
- src/renderer/view/main/BoardPane.vue
- src/renderer/view/main/StandardLayout.vue
- src/renderer/view/main/TabPane.vue
- src/renderer/view/tab/EvaluationChart.vue
- src/tests/common/settings/app.spec.ts
- src/tests/renderer/store/index.spec.ts
> Add dual tab pane feature

- src/background/ipc.ts
- src/background/usi/index.ts
- src/common/settings/research.ts
- src/common/usi.ts
- src/renderer/ipc/api.ts
- src/renderer/ipc/preload.ts
- src/renderer/ipc/setup.ts
- src/renderer/store/analysis.ts
- src/renderer/store/csa.ts
- src/renderer/store/game.ts
- src/renderer/store/index.ts
- src/renderer/store/record.ts
- src/renderer/store/research.ts
- src/renderer/store/usi.ts
- src/renderer/view/dialog/ResearchDialog.vue
- src/renderer/view/tab/EngineAnalytics.vue
- src/renderer/view/tab/EvaluationChart.vue
- src/tests/common/settings/research.spec.ts
- src/tests/renderer/store/index.spec.ts
https://github.com/sunfish-shogi/electron-shogi/issues/263
> Multi Engine Research

- src/common/settings/app.ts
- src/renderer/store/usi.ts
- src/renderer/view/dialog/AppSettingDialog.vue
- src/renderer/view/tab/EngineAnalyticsElement.vue
- src/tests/common/settings/app.spec.ts
https://github.com/sunfish-shogi/electron-shogi/issues/347
> Add EvaluationViewFrom setting

- src/common/shogi/board.ts
- src/common/shogi/direction.ts
- src/common/shogi/index.ts
- src/common/shogi/kakinoki.ts
- src/common/shogi/move.ts
- src/common/shogi/position.ts
- src/common/shogi/record.ts
- src/common/shogi/square.ts
- src/common/shogi/text.ts
- src/renderer/store/analysis.ts
- src/renderer/store/csa.ts
- src/renderer/store/game.ts
- src/renderer/store/index.ts
- src/renderer/store/record.ts
- src/renderer/store/usi.ts
- src/tests/common/shogi/csa.spec.ts
- src/tests/common/shogi/kakinoki.spec.ts
- src/tests/common/shogi/record.spec.ts
- src/tests/common/shogi/text.spec.ts
- src/tests/renderer/store/csa.spec.ts
- src/tests/renderer/store/game.spec.ts
- src/tests/renderer/store/index.spec.ts
https://github.com/sunfish-shogi/electron-shogi/issues/222
> Natural record format (KI2)

- src/renderer/App.vue
- src/renderer/ipc/setup.ts
- src/renderer/store/csa.ts
- src/renderer/store/index.ts
- src/renderer/view/dialog/CSAGameReadyDialog.vue
- src/tests/renderer/store/csa.spec.ts
https://github.com/sunfish-shogi/electron-shogi/issues/357
> enhance CSA login retry

- src/background/log.ts
https://github.com/sunfish-shogi/electron-shogi/issues/363
> lazy loading of Logger

- src/background/ipc.ts
- src/common/ipc/channel.ts
- src/renderer/ipc/api.ts
- src/renderer/ipc/preload.ts
- src/renderer/ipc/web.ts
- src/renderer/view/dialog/USIEngineOptionDialog.vue
> Add open-engine-directorybutton

- public/icon/scoreboard_FILL0_wght400_GRAD0_opsz48.svg
- src/common/helpers/string.ts
- src/renderer/assets/icons.ts
- src/renderer/store/game.ts
- src/renderer/store/index.ts
- src/renderer/view/main/BoardPane.vue
https://github.com/sunfish-shogi/electron-shogi/issues/361
> Add show-game-results button

- src/renderer/view/main/BoardPane.vue
英語の場合にフォントによってはボタンに文字が収まらず改行してしまう問題への対処
> Fix button style

- src/background/usi/engine.ts
- src/common/settings/usi.ts
- src/renderer/view/dialog/USIEngineOptionDialog.vue
- src/tests/common/settings/analysis.spec.ts
- src/tests/common/settings/game.spec.ts
- src/tests/common/settings/research.spec.ts
- src/tests/common/settings/usi.spec.ts
- src/tests/mock/usi.ts
USI Engine が送ってきた順番通りにエンジンオプションを表示するよう改善する。
> Add engine option order

- src/common/i18n/index.ts
- src/common/i18n/translate.ts
- src/common/i18n/usi.ts
- src/common/settings/app.ts
- src/renderer/store/setting.ts
- src/renderer/view/dialog/AppSettingDialog.vue
- src/renderer/view/dialog/USIEngineOptionDialog.vue
- src/tests/common/settings/app.spec.ts
https://github.com/sunfish-shogi/electron-shogi/issues/67
> translate USI engine option names

- public/icon/grid_on_FILL0_wght400_GRAD0_opsz48.svg
- src/background/image.ts
- src/background/ipc.ts
- src/background/menu.ts
- src/common/control/menu.ts
- src/common/control/state.ts
- src/common/graphics.ts
- src/common/i18n/translate.ts
- src/common/ipc/channel.ts
- src/renderer/App.vue
- src/renderer/assets/icons.ts
- src/renderer/ipc/api.ts
- src/renderer/ipc/preload.ts
- src/renderer/ipc/setup.ts
- src/renderer/ipc/web.ts
- src/renderer/store/index.ts
- src/renderer/view/dialog/ExportBoardImageDialog.vue
- src/renderer/view/dialog/PVPreviewDialog.vue
- src/renderer/view/main/BoardPane.vue
- src/renderer/view/main/StandardLayout.vue
- src/renderer/view/main/TabPane.vue
- src/renderer/view/menu/FileMenu.vue
- src/renderer/view/primitive/BoardLayout.ts
- src/renderer/view/primitive/BoardView.vue
- src/renderer/view/primitive/Types.ts
- src/renderer/view/tab/EngineAnalytics.vue
- src/renderer/view/tab/EvaluationChart.vue
- src/renderer/view/tab/RecordInfo.vue
- src/tests/renderer/view/board.spec.ts
https://github.com/sunfish-shogi/electron-shogi/issues/252
> Add board image export feature

- src/common/i18n/errors.ts
- src/common/i18n/record.ts
- src/common/i18n/translate.ts
- src/common/settings/app.ts
- src/common/settings/usi.ts
- src/renderer/helpers/path.ts
- src/renderer/ipc/api.ts
- src/renderer/ipc/preload.ts
- src/renderer/ipc/setup.ts
- src/renderer/ipc/web.ts
- src/renderer/store/index.ts
- src/renderer/store/research.ts
- src/renderer/store/setting.ts
- src/tests/background/csa/client.spec.ts
- src/tests/common/settings/csa.spec.ts
- src/tests/renderer/players/usi.spec.ts
- src/tests/renderer/store/csa.spec.ts
- src/tests/renderer/store/game.spec.ts
- src/tests/renderer/store/index.spec.ts
https://github.com/sunfish-shogi/electron-shogi/issues/398
> Use "@" instead of ".."

- src/common/shogi/text.ts
- src/renderer/store/index.ts
- src/renderer/store/record.ts
- src/renderer/view/tab/EngineAnalyticsElement.vue
- src/renderer/view/tab/RecordComment.vue
- src/tests/common/shogi/text.spec.ts
https://github.com/sunfish-shogi/electron-shogi/issues/259
> Add in-comment PV preview feature

- src/renderer/view/tab/RecordComment.vue
https://github.com/sunfish-shogi/electron-shogi/issues/402
> fix textarea style

- src/renderer/view/main/StandardLayout.vue
https://github.com/sunfish-shogi/electron-shogi/issues/402
> Fix multi pane layout

- src/background/image.ts
- src/background/ipc.ts
- src/common/settings/app.ts
- src/renderer/helpers/path.ts
- src/renderer/store/setting.ts
- src/tests/common/settings/app.spec.ts
https://github.com/sunfish-shogi/electron-shogi/issues/416
> enhance default path of file dialog

- src/common/settings/usi.ts
- src/tests/common/settings/usi.spec.ts
https://github.com/sunfish-shogi/electron-shogi/pull/448
> fix empty default value bug

- src/background/index.ts
https://github.com/sunfish-shogi/electron-shogi/issues/328
> fix to handle uncaughtException

- src/background/index.ts
https://github.com/sunfish-shogi/electron-shogi/issues/328
> fix to handle uncaughtException (v1.5 patch)

- src/background/index.ts
https://github.com/sunfish-shogi/electron-shogi/issues/328
> fix to handle uncaughtException (v1.6 patch)

- src/renderer/store/index.ts
https://github.com/sunfish-shogi/electron-shogi/issues/459
> enhance save-record dialog behavior

- src/renderer/view/dialog/USIEngineOptionDialog.vue
https://github.com/sunfish-shogi/electron-shogi/issues/445
> display default value of engine options

- src/background/csa/client.ts
- src/tests/background/csa/client.spec.ts
- https://github.com/sunfish-shogi/electron-shogi/issues/473
- https://github.com/sunfish-shogi/electron-shogi/issues/471
- https://github.com/sunfish-shogi/electron-shogi/issues/474
> Fix CSA protocol (v1.5)

- src/background/csa/client.ts
- src/tests/background/csa/client.spec.ts
- https://github.com/sunfish-shogi/electron-shogi/issues/473
- https://github.com/sunfish-shogi/electron-shogi/issues/471
- https://github.com/sunfish-shogi/electron-shogi/issues/474
> Fix CSA protocol (v1.6)

- src/background/csa/client.ts
- src/tests/background/csa/client.spec.ts
- https://github.com/sunfish-shogi/electron-shogi/issues/473
- https://github.com/sunfish-shogi/electron-shogi/issues/471
- https://github.com/sunfish-shogi/electron-shogi/issues/474
> Fix CSA Protocol

- src/background/image.ts
- src/background/ipc.ts
- src/common/ipc/channel.ts
- src/renderer/ipc/api.ts
- src/renderer/ipc/preload.ts
- src/renderer/ipc/setup.ts
- src/renderer/ipc/web.ts
https://github.com/sunfish-shogi/electron-shogi/issues/491
- MUST
> fix to propagate app setting change to renderer process

- src/background/csa/client.ts
- src/renderer/store/csa.ts
- src/tests/background/csa/client.spec.ts
- src/tests/mock/csa.ts
- src/tests/renderer/store/csa.spec.ts
https://github.com/sunfish-shogi/electron-shogi/issues/472
https://github.com/sunfish-shogi/electron-shogi/issues/478
- MUST
> Update csa client

- public/icon/add_circle_FILL0_wght400_GRAD0_opsz48.svg
- src/common/settings/research.ts
- src/renderer/assets/icons.ts
- src/renderer/store/research.ts
- src/renderer/view/dialog/AnalysisDialog.vue
- src/renderer/view/dialog/ResearchDialog.vue
- src/tests/common/settings/research.spec.ts
- src/tests/mock/research.ts
- src/tests/renderer/store/research.spec.ts
https://github.com/sunfish-shogi/electron-shogi/issues/417
- MUST
> Add maxSeconds setting to ResearchDialog

- src/background/image/cache.ts
- src/background/image/cropper.ts
- src/background/ipc.ts
- src/background/settings.ts
- src/common/ipc/channel.ts
- src/common/settings/app.ts
- src/renderer/helpers/path.ts
- src/renderer/ipc/api.ts
- src/renderer/ipc/preload.ts
- src/renderer/ipc/web.ts
- src/renderer/view/dialog/AppSettingDialog.vue
- src/renderer/view/dialog/ExportPositionImageDialog.vue
- src/renderer/view/dialog/PVPreviewDialog.vue
- src/renderer/view/main/BoardPane.vue
- src/renderer/view/primitive/BoardLayout.ts
- src/renderer/view/primitive/BoardView.vue
- src/tests/common/settings/app.spec.ts
- src/tests/renderer/helpers/path.spec.ts
- src/tests/renderer/store/research.spec.ts
- src/tests/renderer/view/board.spec.ts
- webpack.config.js
リファクタリングと Lint に対する修正など
- MUST
> refactoring and lint fix

- src/renderer/helpers/path.ts
- src/renderer/store/index.ts
- src/tests/renderer/helpers/path.spec.ts
https://github.com/sunfish-shogi/electron-shogi/issues/505
- MUST
> Fix record file name bug

- src/common/helpers/metadata.ts
- src/common/i18n/locales/en.ts
- src/renderer/view/dialog/ExportPositionImageDialog.vue
- src/renderer/view/dialog/PVPreviewDialog.vue
- src/renderer/view/main/BoardPane.vue
> refactoring

- src/renderer/store/analysis.ts
- src/renderer/store/record.ts
- src/tests/renderer/store/analysis.spec.ts
- src/tests/renderer/store/record.spec.ts
解析や対局におけるコメント出力の内容を充実させる。
https://github.com/sunfish-shogi/electron-shogi/issues/411
- MUST
> enhance search comment

- src/background/ipc.ts
- src/background/usi/engine.ts
- src/background/usi/index.ts
- src/common/i18n/locales/en.ts
- src/common/i18n/locales/ja.ts
- src/common/i18n/locales/zh_tw.ts
- src/common/i18n/text_template.ts
- src/common/ipc/channel.ts
- src/renderer/ipc/api.ts
- src/renderer/ipc/preload.ts
- src/renderer/ipc/web.ts
- src/renderer/players/human.ts
- src/renderer/players/player.ts
- src/renderer/players/usi.ts
- src/renderer/store/analysis.ts
- src/renderer/store/csa.ts
- src/renderer/store/game.ts
- src/renderer/store/research.ts
- src/tests/mock/player.ts
- src/tests/renderer/store/csa.spec.ts
- src/tests/renderer/store/game.spec.ts
- src/tests/renderer/store/research.spec.ts
https://github.com/sunfish-shogi/electron-shogi/issues/501
連続対局や CSA サーバーへの再接続をした際に、 USI エンジンのプロセスをキープするよう改善します。
- MUST
> update USI engine management

- src/background/usi/engine.ts
- src/background/usi/index.ts
- src/background/usi/process.ts
- src/renderer/store/mate.ts
- src/tests/background/usi/engine.spec.ts
https://github.com/sunfish-shogi/electron-shogi/issues/509
EngineProcess クラスを改善し、ユニットテストを作成する。
- MUST
> Enhance EngineProcess and add its tests

- src/common/i18n/locales/en.ts
- src/common/i18n/locales/ja.ts
- src/common/i18n/locales/zh_tw.ts
- src/common/i18n/text_template.ts
- src/renderer/store/index.ts
- src/renderer/store/record.ts
- src/renderer/view/dialog/InfoMessage.vue
Shift_JIS で保存したときに文字化けする文字が含まれているか検査して、必要に応じてメッセージを表示します。
- MUST
> garbled character detection

- src/common/i18n/locales/en.ts
- src/common/i18n/locales/ja.ts
- src/common/i18n/locales/zh_tw.ts
- src/common/i18n/text_template.ts
- src/common/settings/csa.ts
- src/common/settings/game.ts
- src/common/settings/research.ts
> Translate some error messages

- package-lock.json
- src/common/i18n/locales/zh_tw.ts
> add zh_tw translation

- scripts/build.mjs
AppImage がビルドできない問題を修正する。
- MUST
> Fix build script

- src/common/settings/app.ts
- src/renderer/view/dialog/AppSettingDialog.vue
- src/renderer/view/primitive/BoardLayout.ts
#555 
盤と駒台それぞれに「紅葉」「雪」を追加
- MUST
> Add new board types

- src/common/shogi/kakinoki.ts
- src/tests/common/shogi/kakinoki.spec.ts
> Fix to allow half size colon

- src/renderer/view/primitive/RecordView.vue
> Fix css of RecordView

- src/common/i18n/locales/en.ts
- src/common/i18n/locales/ja.ts
- src/common/i18n/locales/zh_tw.ts
- src/common/i18n/text_template.ts
- src/common/settings/app.ts
- src/renderer/css/color.css
- src/renderer/view/dialog/AppSettingDialog.vue
- src/renderer/view/primitive/BoardLayout.ts
> Add dark green

- src/renderer/view/dialog/AppSettingDialog.vue
> fix layout

- src/common/i18n/locales/zh_tw.ts
Traditional Chinese Update
- MUST
> ZH_TW Translation Update

- src/common/shogi/record.ts
- src/tests/common/shogi/record.spec.ts
Record クラスの forEach のハンドラーに渡される局面が間違っていたのを修正する。
- MUST
> Fix Record#forEach

- docs/index.en.html
- docs/index.html
- docs/index.zh_tw.html
This is the update only applies on homepage, and have no affect to source code of app. 
- MUST
> add zh_tw homepage translation

- src/background/conversion.ts
- src/common/settings/app.ts
- src/renderer/store/index.ts
- src/renderer/store/setting.ts
- src/renderer/view/dialog/AppSettingDialog.vue
- src/tests/background/conversion.spec.ts
USI 形式に関するアプリ設定項目について、エンジンとのやりとりとファイル I/O を明確に区別するために、ファイル I/O 関係には `File` を含めるように修正する。
- MUST
> Rename USI file settings

- scripts/build.mjs
#597 
拡張子 `.jkf` を Electron 将棋に関連付ける。
- MUST
> Add .jkf as related extension

- src/renderer/view/dialog/CSAGameDialog.vue
- src/renderer/view/dialog/PasteDialog.vue
- src/renderer/view/primitive/BoardView.vue
- src/renderer/view/primitive/SimpleBoardView.vue
- src/renderer/view/tab/RecordComment.vue
厳密な文法に準拠していないタグの書き方を修正する。
- MUST
> Fix some HTML tags

- src/renderer/view/primitive/BoardLayout.ts
- src/renderer/view/primitive/BoardView.vue
透過機能の不具合で、駒台だけでなく駒まで透過の対象になっていたのを修正する。
- MUST
> Fix transparent feature

- src/background/conversion.ts
- src/background/helpers/file.ts
- src/background/image/capture.ts
- src/background/image/cropper.ts
- src/background/index.ts
- src/background/ipc.ts
- src/background/log.ts
- src/background/settings.ts
- src/tests/background/conversion.spec.ts
> non-blocking I/O の適用範囲を拡大

- src/background/ipc.ts
- src/background/usi/index.ts
> non-functional fix

- src/renderer/store/usi.ts
- src/renderer/view/tab/EngineAnalyticsElement.vue
- src/tests/renderer/store/index.spec.ts
> Add iteration ID and v-memo

- src/renderer/view/tab/EvaluationChart.vue
Chart.js の更新処理が重いので 0.1 秒遅延させてから更新する。
#645 
- MUST
> グラフの描画を遅延実行して棋譜の閲覧を滑らかにする改善

- src/background/image/cropper.ts
- src/background/ipc.ts
- src/common/i18n/locales/en.ts
- src/common/i18n/locales/ja.ts
- src/common/i18n/locales/zh_tw.ts
- src/common/i18n/text_template.ts
- src/common/ipc/channel.ts
- src/common/settings/app.ts
- src/renderer/ipc/api.ts
- src/renderer/ipc/preload.ts
- src/renderer/ipc/web.ts
- src/renderer/store/setting.ts
- src/renderer/view/dialog/AppSettingDialog.vue
- src/tests/background/image/cropper.spec.ts
> カスタム駒画像の余白を除去して大きく表示するオプションを追加

- public/icon/pause_circle_FILL0_wght400_GRAD0_opsz24.svg
- public/icon/play_circle_FILL0_wght400_GRAD0_opsz24.svg
- src/common/i18n/locales/en.ts
- src/common/i18n/locales/ja.ts
- src/common/i18n/locales/zh_tw.ts
- src/common/i18n/text_template.ts
- src/renderer/assets/icons.ts
- src/renderer/players/usi.ts
- src/renderer/store/index.ts
- src/renderer/store/research.ts
- src/renderer/view/tab/EngineAnalytics.vue
- src/renderer/view/tab/EngineAnalyticsElement.vue
- src/tests/renderer/store/research.spec.ts
> 検討中にエンジンを起動したまま思考を一時停止する機能

- src/renderer/App.vue
- src/renderer/view/dialog/PositionImageExportDialog.vue
> Fix PositionImageExportDialog bug

- package.json
- src/background/index.ts
https://github.com/sunfish-shogi/electron-shogi/issues/667
[backgroundThrottling](https://www.electronjs.org/docs/latest/api/browser-window#page-visibility) を無効化して、画面が非表示の状態でも処理を遅延させない改善。
- MUST
> Disable backgroundThrottling

- .github/workflows/test.yml
- .prettierignore
- docs-templates/index.en.html
- docs-templates/index.html
- docs-templates/index.zh_tw.html
- docs/release.json
- package-lock.json
- package.json
- scripts/fake-release-api.mjs
- scripts/publish-release.ts
- src/background/helpers/electron.ts
- src/background/helpers/http.ts
- src/background/index.ts
- src/background/menu.ts
- src/background/version/check.ts
- src/background/version/types.ts
- src/common/i18n/locales/en.ts
- src/common/i18n/locales/ja.ts
- src/common/i18n/locales/zh_tw.ts
- src/common/i18n/text_template.ts
- src/tests/background/version.spec.ts
#661 
アプリ起動時に新しいバージョンがあるかチェックして新しいバージョンを通知する。
- MUST
> 新しいリリースを通知する機能

- public/icon/help_FILL0_wght400_GRAD0_opsz24.svg
- src/background/window/ipc.ts
- src/common/i18n/locales/en.ts
- src/common/i18n/locales/ja.ts
- src/common/i18n/locales/zh_tw.ts
- src/common/i18n/text_template.ts
- src/common/ipc/channel.ts
- src/common/settings/app.ts
- src/renderer/assets/icons.ts
- src/renderer/helpers/path.ts
- src/renderer/ipc/api.ts
- src/renderer/ipc/preload.ts
- src/renderer/ipc/web.ts
- src/renderer/store/index.ts
- src/renderer/store/setting.ts
- src/renderer/view/dialog/AppSettingDialog.vue
- src/tests/renderer/helpers/path.spec.ts
#685 
解説ページ: [棋譜ファイル名テンプレート](https://github.com/sunfish-shogi/electron-shogi/wiki/%E6%A3%8B%E8%AD%9C%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E5%90%8D%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88)
- MUST
> 棋譜ファイル名のテンプレートを設定する機能

- src/background/window/menu.ts
> Add accelerator for Mac

- scripts/build.mjs
> macOS向けにユニバーサルアプリを提供する。

- package-lock.json
- package.json
- src/background/index.ts
- src/common/i18n/locales/en.ts
- src/common/i18n/locales/ja.ts
- src/common/i18n/locales/zh_tw.ts
- src/common/i18n/text_template.ts
#700 
右クリックで「切り取り」「コピー」「貼り付け」を含むメニューを表示できるようにする。
- MUST
> テキスト入力欄の右クリックメニュー

- package.json
- scripts/publish-release.ts
新しいバージョンのリリースコミットを作成するスクリプトを追加する。
- MUST
> Add release script

- src/background/csa/client.ts
パスワードが空文字の場合にログを置換しないよう修正。
- MUST
> Fix for empty password

- src/common/i18n/locales/en.ts
- src/common/i18n/locales/ja.ts
- src/common/i18n/locales/zh_tw.ts
- src/common/i18n/text_template.ts
- src/common/settings/csa.ts
- src/renderer/view/dialog/CSAGameDialog.vue
- src/renderer/view/dialog/ConnectToCSAServerDialog.vue
- src/tests/common/settings/csa.spec.ts
CSA プロトコルの ID やパスワードに空白が含まれていないことを検査する。
- MUST
> Add validation for CSA server setting

- src/common/i18n/text_template.ts
- src/renderer/view/dialog/USIEngineOptionDialog.vue
早期 Ponder の設定を USI_Ponder と一緒に配置する。
- MUST
> Update engine option dialog

- .github/workflows/test.yml
https://github.com/codecov/codecov-action
- MUST
> Fix codecov setting

- package.json
- plugins/webpack.cjs
- scripts/distribute-command.mjs
- src/background/file/history.ts
- src/background/helpers/electron.ts
- src/background/helpers/encrypt.ts
- src/background/helpers/portability.ts
- src/background/image/cache.ts
- src/background/image/capture.ts
- src/background/log.ts
- src/background/proc/env.ts
- src/background/settings.ts
- src/command/common/arguments.ts
- src/command/usi-csa-bridge/README.md
- src/command/usi-csa-bridge/index.ts
- src/common/i18n/locales/en.ts
- src/common/i18n/locales/ja.ts
- src/common/i18n/locales/zh_tw.ts
- src/common/i18n/text_template.ts
- src/common/settings/csa.ts
- src/renderer/view/dialog/CSAGameDialog.vue
- src/tests/command/common/arguments.spec.ts
- tsconfig.cmd.json
- webpack.config.cjs
> Release usi-csa-bridge

- src/renderer/store/research.ts
検討中、局面を変更した直後にエンジンから変更前の局面の評価値を受信すると、変更後の局面の評価値としてグラフに表示してしまう不具合があった。
検討中の動作の改善のため、エンジンへのコマンド送信を意図的に遅延させる実装 #518 を入れたが、遅延した 200ms の間に受信した情報の取り扱いが不適切だった。
- MUST
> 検討中の評価値グラフの表示不具合を修正

- src/renderer/store/index.ts
- src/renderer/store/record.ts
> Add backup handler

- src/command/common/arguments.ts
- src/command/common/preload.ts
- src/command/usi-csa-bridge/index.ts
- src/tests/command/common/arguments.spec.ts
> Add command options

- src/background/csa/client.ts
- src/background/csa/index.ts
- src/background/usi/engine.ts
- src/command/common/arguments.ts
- src/common/helpers/encode.ts
- src/common/settings/research.ts
- src/common/settings/usi.ts
- src/renderer/helpers/dialog.ts
- src/renderer/helpers/lazy.ts
- src/renderer/players/human.ts
- src/renderer/players/usi.ts
- src/renderer/store/clock.ts
- src/renderer/store/csa.ts
- src/renderer/store/game.ts
- src/renderer/store/index.ts
- src/renderer/store/mate.ts
- src/renderer/view/dialog/AppSettingDialog.vue
- src/renderer/view/dialog/USIEngineManagementDialog.vue
- src/renderer/view/prompt/CommandHistory.vue
- src/renderer/view/tab/EngineAnalyticsElement.vue
分岐をリファクタリングしました。
- オプショナルチェーンや論理式の整理によって不要になる分岐を削除
- for + if をfilter()、forEach()、some()によって宣言的な記述に変更
- MUST
> refactor: clean branch

- .github/workflows/test.yml
- src/background/usi/engine.ts
- src/background/usi/index.ts
- src/background/window/ipc.ts
- src/common/game/time.ts
- src/renderer/ipc/api.ts
- src/renderer/ipc/preload.ts
- src/renderer/players/human.ts
- src/renderer/players/player.ts
- src/renderer/players/usi.ts
- src/renderer/store/clock.ts
- src/renderer/store/csa.ts
- src/renderer/store/game.ts
- src/tests/mock/player.ts
- src/tests/renderer/players/usi.spec.ts
> Fix time management issue (v1.13)

- src/renderer/players/usi.ts
- src/tests/renderer/players/usi.spec.ts
> Fix to keep available search info (v1.12)

- src/renderer/players/usi.ts
- src/tests/renderer/players/usi.spec.ts
> Fix to keep available search info (v1.13)

- src/background/usi/engine.ts
- src/tests/background/usi/engine.spec.ts
> Fix USI command parser bug (v1.12)

- src/background/usi/engine.ts
- src/tests/background/usi/engine.spec.ts
> Fix USI command parser bug (v1.13)

- src/renderer/helpers/dialog.ts
- src/renderer/view/dialog/AnalysisDialog.vue
- src/renderer/view/dialog/AppSettingDialog.vue
- src/renderer/view/dialog/BatchConversionDialog.vue
- src/renderer/view/dialog/BookmarkListDialog.vue
- src/renderer/view/dialog/CSAGameDialog.vue
- src/renderer/view/dialog/ConnectToCSAServerDialog.vue
- src/renderer/view/dialog/ErrorMessage.vue
- src/renderer/view/dialog/GameDialog.vue
- src/renderer/view/dialog/InfoMessage.vue
- src/renderer/view/dialog/LaunchUSIEngineDialog.vue
- src/renderer/view/dialog/MateSearchDialog.vue
- src/renderer/view/dialog/PVPreviewDialog.vue
- src/renderer/view/dialog/PasteDialog.vue
- src/renderer/view/dialog/PositionImageExportDialog.vue
- src/renderer/view/dialog/RecordFileHistoryDialog.vue
- src/renderer/view/dialog/ResearchDialog.vue
- src/renderer/view/dialog/USIEngineManagementDialog.vue
- src/renderer/view/dialog/USIEngineOptionDialog.vue
> Escape キーに対するダイアログの表示不具合を修正 (v1.13)

- src/renderer/view/dialog/PVPreviewDialog.vue
> 読み筋プレビューダイアログからコメントを挿入した時の不具合を修正 (v1.13)

- package-lock.json
> npm-update

- src/renderer/view/tab/EngineAnalyticsElement.vue
> update css of engine analytics

- src/background/window/main.ts
> Fix not to show update-check-failure message

- src/common/links/github.ts
- src/renderer/store/index.ts
- src/renderer/view/dialog/ShareDialog.vue
- src/renderer/view/menu/FileMenu.vue
- src/renderer/view/primitive/board/hand.ts
- src/tests/common/links/github.spec.ts
> Update mobile app

- package.json
- src/tests/renderer/store/usi.bench.ts
> Add benchmark test

- docs/index.en.html
- docs/index.html
- docs/index.zh_tw.html
- docs/release-linux.json
- docs/release-mac.json
- docs/release-win.json
- docs/release.json
- https://github.com/sunfish-shogi/electron-shogi/releases/tag/v1.17.1
- https://github.com/sunfish-shogi/electron-shogi/releases/tag/v1.16.1
- MUST
> Release v1.17.1 and v1.16.1

- src/renderer/view/dialog/USIEngineOptionsDialog.vue
> 既定値から変更したエンジン設定をハイライトする改善
