src/ipc/background.ts

例えば、以下のような手順で導入できる [WebAssembly版やねうら王（現在はテスト版）](https://github.com/mizar/YaneuraOu.wasm)のような、`cmd`,`bat`拡張子から起動できるUSIエンジンをファイル一覧から選択できるようにします。
> 1. Node.js をインストール
> https://nodejs.org/ja/
> 
> 2. Windows+R キー操作 「ファイル名を指定して実行」 欄に以下を入力して実行
> ```
> npm -g i @mizarjp/yaneuraou.k-p@latest @mizarjp/yaneuraou.material@latest @mizarjp/yaneuraou.material9@latest @mizarjp/yaneuraou.komoringheights-mate@latest
> ```
> 
> 3. 実行ファイルをGUIに登録
> 
> SuishoPetit（k-p:軽量版NNUE）の場合
> 
> - 将棋所: メニューバーより「対局(G)」→「エンジン管理...」→「追加...」→ファイル名入力欄に `"%APPDATA%\npm\usi.k-p.cmd"` と入力して「開く(O)」
> - ShogiGUI: メニューバーより「ツール(T)」→「エンジン設定(E)」→「追加」→ファイル名入力欄に `"%APPDATA%\npm\usi.k-p.cmd"` と入力して「開く(O)」
> 
> 以下、同様に
> 
> - SuishoPetit（k-p:軽量版NNUE）:
> ```
> "%APPDATA%\npm\usi.k-p.cmd"
> ```
> - MaterialLv1（静的評価関数Lv1: 駒得のみ）:
> ```
> …
```

windows: add file suffix for cmd, bat

---

src/components/primitive/BoardLayout.ts

https://github.com/sunfish-shogi/electron-shogi/issues/71
1 筋や 9 筋で成・不成の選択を出す際に、盤からはみ出さないように修正します。

fix promotion UI layout #71

---

src/components/dialog/PVPreviewDialog.vue
src/components/tab/EngineAnalyticsElement.vue

https://github.com/sunfish-shogi/electron-shogi/pull/139 で、読み筋をオーバーレイで盤面表示できる機能を実装した。
しかし、「思考」タブの情報と重なってしまい、かつ思考中の場合はタブ内の情報がどんどん更新されてしまうので、評価値や深さの情報がいくつだったかは画面上でわからなくなってしまう。
そこで、オーバーレイ表示した盤面の下部にテキストベースの読み筋や評価値、探索深さ等の情報を表示する。

Update pv preview

---

src/shogi/position.ts
src/shogi/record.ts
tests/unit/shogi/csa.spec.ts
tests/unit/shogi/kakinoki.spec.ts
tests/unit/shogi/position.spec.ts

関連: https://github.com/sunfish-shogi/electron-shogi/issues/17
Position クラスで sfen 形式の局面表記を生成した際に `sfen ` というプレフィクスを付与していたのをやめる。

Change sfen behavior not to append "sfen" prefix

---

src/shogi/record.ts
src/store/index.ts
tests/unit/store/index.spec.ts

指し手削除で確認ダイアログを出すかどうかについて、分岐があった場合の振る舞いを修正。

Fix removeRecordAfter

---

src/shogi/csa.ts
tests/unit/shogi/csa.spec.ts

http://www2.computer-shogi.org/protocol/record_v22.html
> セパレータ("/"だけの行)をはさんで、これらデータを繰り返し、複数の棋譜や局面を示すことができる。
スラッシュ `/` だけの行を挟むと複数の棋譜を記述できるという CSA 棋譜ファイルの仕様に対して、 2 つ目以降の棋譜は読み込まないつもりだったが、総実装できておらずエラーを起こしてしまう状態だったので修正する。

Fix import error of CSA multi-records

---

src/shogi/record.ts
src/store/index.ts
src/store/record.ts

https://github.com/sunfish-shogi/electron-shogi/pull/185 で Record 管理について変更を行ったが、検討機能を使った際に局面を変更してもそれが伝搬しないようになってしまった。
Vue.js の機能で監視しているつもりだったが、参照の変更は検知できない仕様だった。
Record クラスに機能を追加して局面の変更をハンドルできるようにする。

Fix research bug

---

src/App.vue

ダイアログを表示した際、ページ全体に対してスクロールバーが一瞬表示されて消えたり、あるいはそのまま表示され続ける事がある。
そこで、 CSS によって強制的にスクロールバーを無効化する。

Disable scrollbar of body element

---

src/components/main/BoardPane.vue
src/ipc/background/menu.ts
src/ipc/menu.ts
src/ipc/setup.ts
src/shogi/record.ts
src/store/game.ts
src/store/index.ts
src/store/record.ts
tests/unit/store/index.spec.ts

removeNextMove を新規に作成して、 https://github.com/sunfish-shogi/electron-shogi/issues/217 の問題の修正に使用する。
また、 removeAfter は removeCurrentMove に名前を変更する。

Add removeNextMove

---

src/components/primitive/BoardView.vue
src/shogi/move.ts
tests/unit/shogi/csa.spec.ts
tests/unit/shogi/kakinoki.spec.ts
tests/unit/store/csa.spec.ts
tests/unit/store/game.spec.ts
tests/unit/store/index.spec.ts

KIF 形式以外では `▲` `△` ではなく `☗` `☖` を使うように改善する。
いずれも Unicode に追加されて久しいので文字化け等は問題にならないと思われる。

Use ☗ and ☖

---

src/shogi/move.ts
src/shogi/record.ts
src/store/record.ts
src/store/usi.ts
tests/unit/store/csa.spec.ts
tests/unit/store/game.spec.ts

https://github.com/sunfish-shogi/electron-shogi/issues/249
棋譜コメントに `☗` `☖` を使ってしまうと KIF 形式で文字化けするので棋譜コメントではレガシーな表記を使用する。

Fix garbled characters #249

---

src/store/csa.ts

CSA サーバーに中断要求を出したときに応答を待たずに close していたので、結果が棋譜に入らない上に自動保存が実行されていなかった。

fix not to call close() #292

---

src/components/dialog/AnalysisDialog.vue
src/components/dialog/ResearchDialog.vue

登録されているエンジン名の最大長が短いか、あるいはエンジンが全く無い場合に検討ダイアログと解析ダイアログのレイアウトが崩れる問題を修正する。

fix layout of PlayerSelector

---

src/background/usi/engine.ts

USI エンジン起動時のログで対象のファイルのパスではなく、親ディレクトリのパスが出力されていた問題を修正する。

Fix USI log

---

src/renderer/view/primitive/RecordView.vue

分岐リスト内のコメントが次の行に折り返してしまう問題を修正。
この問題は v1.7.0-alpha.1 から発生していた。

fix record view layout

---

scripts/archive.mjs
scripts/build.mjs
scripts/report-license.mjs

.mjs ではデフォルトで Strict モードになるので、冗長な指定を除去する。

remove "use strict" from mjs

---

src/renderer/view/dialog/USIEngineOptionDialog.vue

https://github.com/sunfish-shogi/electron-shogi/issues/445
USI エンジンオプションの "check" タイプにおいて、デフォルト値が指定されている場合は「既定値」の選択肢を表示しない。

update UI of "check" option

---

package-lock.json
package.json

npm audit で minimatch の ReDoS 脆弱性が報告されるので修正する。
electron-builder から間接的に参照しているパッケージで、しかも ReDoS 脆弱性なので、 Electron 将棋に実害があるとは考えられないが毎度警告されるので回避しておく。

upgrade minimatch

---

src/common/i18n/locales/en.ts
src/common/i18n/locales/ja.ts
src/common/i18n/locales/zh_tw.ts
src/common/i18n/text_template.ts
src/renderer/view/dialog/MateSearchDialog.vue

MateSearchDialog の多言語対応が漏れていたので修正します。
https://github.com/sunfish-shogi/electron-shogi/issues/489
- MUST

translate MateSearchDialog

---

src/common/i18n/locales/en.ts
src/common/i18n/locales/ja.ts
src/common/i18n/locales/zh_tw.ts
src/common/i18n/text_template.ts
src/renderer/view/dialog/CSAGameDialog.vue

- 評価値送信を WCSC で使わないよう促すワーニングを廃止する。
https://github.com/sunfish-shogi/electron-shogi/issues/498
- 履歴を使用した際にワーニングが表示されないことがある問題を修正する。
- MUST

Remove warning message for extended CSA protocol

---

src/background/usi/engine.ts

エンジンから `score mate -0` を送られると、それを正の値として扱っていた問題を修正する。
https://github.com/sunfish-shogi/electron-shogi/issues/507
- MUST

Fix score-mate bug

---

package-lock.json
package.json

jimp から間接的に依存している xml2js の脆弱性がある。
ElectronShogi にとって問題は無いと思うが、 Dependabot の警告を消したいので v0.5.0 以上へ強制的にアップデートする。
- MUST

fix for npm-audit

---

src/renderer/store/record.ts
src/renderer/store/research.ts
src/tests/renderer/store/index.spec.ts
src/tests/renderer/store/research.spec.ts

検討機能に関する以下の変更を加えます。
- 1 手あたりの時間を指定した場合に、局面を変更しても残り時間がリセットされない問題を修正
- 読み筋を棋譜へ挿入した際にエンジンへ無駄なコマンドを送る問題を修正
- 高頻度で局面を変更した場合の動作を改善
- MUST

検討機能の不具合修正

---

src/background/ipc.ts
src/common/i18n/locales/en.ts
src/common/i18n/locales/ja.ts
src/common/i18n/locales/zh_tw.ts
src/common/i18n/text_template.ts
src/common/settings/app.ts
src/renderer/helpers/path.ts
src/renderer/store/index.ts
src/renderer/store/setting.ts
src/renderer/view/dialog/AppSettingDialog.vue

https://github.com/sunfish-shogi/electron-shogi/issues/521
デフォルトの棋譜ファイル形式をアプリ設定で選べるようにします。
- MUST

Add defaultRecordFileFormat setting

---

scripts/build.mjs

#523 
アプリインストール時に棋譜ファイルの拡張子を Electron 将棋に関連付ける。
- MUST

associate supported file extensions

---

src/background/index.ts
src/background/ipc.ts
src/common/i18n/locales/en.ts
src/common/i18n/locales/ja.ts
src/common/i18n/locales/zh_tw.ts
src/common/i18n/text_template.ts
src/common/ipc/channel.ts
src/renderer/ipc/api.ts
src/renderer/ipc/preload.ts
src/renderer/ipc/setup.ts
src/renderer/ipc/web.ts

#522 
macOS の Finder から棋譜ファイルを開けるようにします。
参考:
https://zenn.dev/sprout2000/books/3691a679478de2/viewer/13483
https://zenn.dev/sprout2000/books/3691a679478de2/viewer/13498#macos-%E3%81%AE%E5%A0%B4%E5%90%88
- MUST

Add open-file event handling for macOS

---

src/background/image/cropper.ts

#532 
カスタム駒画像を使用した場合に、玉（2, 4行目1列）を先手、王（1, 3行目1列）を後手の駒として表示するように修正する。
- MUST

fix to use Gyoku as piece of Sente

---

src/common/i18n/locales/en.ts
src/common/i18n/locales/ja.ts
src/common/i18n/locales/zh_tw.ts
src/common/i18n/text_template.ts
src/renderer/store/index.ts
src/tests/renderer/store/index.spec.ts

ファイルを開けないステータスのときに、ファイルを D&D などで開こうとする行為に対してエラーメッセージを表示する。
関連: https://github.com/sunfish-shogi/electron-shogi/issues/537
- MUST

Add error message when failed to open record by unexpected state

---

src/renderer/view/primitive/BoardView.vue

Electron将棋の初期からあった標準の駒画像と縦横比が異なる画像を使用すると比率が強制的に変えられます。
これを画像素材の比が保たれる様に修正します。
https://github.com/sunfish-shogi/electron-shogi/issues/294#issuecomment-1602573769
**修正前**
**修正後**
- MUST

Fix piece image layout

---

src/renderer/store/csa.ts
src/tests/renderer/store/csa.spec.ts

#550 
CSA プロトコルでの途中局面再開で対局を正常に開始できない不具合の修正
- MUST

fix initial position bug for CSA game

---

src/common/shogi/record.ts
src/tests/common/shogi/record.spec.ts

Fix not to call onChangePosition without ply changes

---

src/background/usi/engine.ts
src/background/usi/index.ts
src/background/usi/process.ts
src/renderer/view/dialog/CSAGameReadyDialog.vue
src/tests/background/usi/engine.spec.ts

#558 
USI プロトコル上で isready/readyok/usinewgame のやり取りを完了してから CSA サーバーにログインをしている。
正常に対局を終えた場合には gameover コマンドを送信するが、 CSA サーバーから REJECT された場合や、CSA サーバーとの接続が切れた場合に gameover を送信しない。
この状態のまま再試行すると unexpected state エラーで処理が進まなくなる。
この問題は v1.8 でエンジンプロセスを使い回すようになったことで生じた。
v1.7 ではエンジンプロセスを再試行や対局とともに終了していたので、問題が表面化しなかった。
前回のゲームが終了されないまま ready 関数が呼ばれた場合は、自動的に gameover コマンドを送信してからゲームを終わらせるよう修正する。
- MUST

Fix to send gameover command when game was not ended normally

---

src/renderer/ipc/setup.ts
src/renderer/players/usi.ts

v1.7 から Ponder 中の読み筋と評価値グラフ表示に不具合があった。
- 読み筋: Ponder の読み筋が表示に反映されない。
- 評価値グラフ: Ponder 中に評価値が相手のプロットとして表示される。
setup.ts の書き間違いで onPonderInfo 関数を呼び出せていなかったので修正する。
- MUST

Fix usi ponder info bug

---

src/renderer/store/csa.ts

#561 
コネクションエラー等による対局の中断時にも棋譜を自動保存するように修正します。
- MUST

Fix to save record irrespective of server status

---

src/renderer/store/csa.ts
src/tests/renderer/store/csa.spec.ts

Web アプリで CSA プロトコルを利用しようとしたときに、再接続のダイアログと対局設定のダイアログが同時に表示されて操作できなくなる問題を修正する。
- MUST

Fix not to return error

---

src/renderer/view/dialog/AppSettingDialog.vue
src/renderer/view/menu/FileMenu.vue

自動保存先をファイルメニューやアプリ設定内から開けるようにボタンを設定する。
- MUST

Add menu button for auto-save directory

---

src/common/shogi/kakinoki.ts
src/common/shogi/position.ts
src/common/shogi/record.ts
src/tests/common/shogi/kakinoki.spec.ts
src/tests/common/shogi/record.spec.ts

KI2 出力の不具合を修正する。
「右」「打」などの修飾をするための Position に常に初期局面を渡してしまっていて正しい判定処理ができていなかった。
- MUST

Fix exportKI2 bug

---

src/renderer/view/dialog/AppSettingDialog.vue

アプリ設定ダイアログにおいて、ディレクトリを開くボタンが入力中の値ではなく変更前の値を参照していた問題を修正する。
- MUST

Fix app setting dialog

---

src/common/shogi/kakinoki.ts
src/tests/common/shogi/kakinoki.spec.ts

- 入玉勝ちのときの最終行の記述を修正
- メタデータの値にコロンが含まれている場合の挙動を修正
- MUST

KIF/KI2 の微修正

---

src/common/shogi/record.ts
src/tests/common/shogi/record.spec.ts
src/tests/renderer/players/usi.spec.ts
src/tests/renderer/store/csa.spec.ts
src/tests/renderer/store/game.spec.ts
src/tests/renderer/store/index.spec.ts
src/tests/renderer/store/research.spec.ts

USI プロトコルの仕様によれば、平手の初期局面は SFEN ではなく startpos を使うことが推奨されているように読める。
http://shogidokoro.starfree.jp/usi.html
> 初期局面の部分については、平手初期局面であれば単にstartposと書き、そうでなければsfenに続けてSFENの書式に基づいて記述します。
このドキュメント自体は将棋所を強く意識した内容なので、どの程度の推奨事項なのかニュアンスが微妙なところはあるが従う方が無難だと思うのでそうする。
これによってコマンドの文字数が減る。パフォーマンス上の違いは誤差だと思うが、ログが見やすくなるメリットが有る。
- MUST

平手の場合に USI position コマンドで startpos を使用するように変更

---

src/background/usi/engine.ts
src/common/usi.ts
src/renderer/store/record.ts
src/tests/background/usi/engine.spec.ts
src/tests/renderer/store/record.spec.ts

#591 
コメント内メタデータ「詰み」を実装する。
仕様: https://github.com/sunfish-shogi/electron-shogi/wiki/%E6%80%9D%E8%80%83%E3%82%B3%E3%83%A1%E3%83%B3%E3%83%88%E3%81%AE%E4%BB%95%E6%A7%98%EF%BC%88%E3%83%89%E3%83%A9%E3%83%95%E3%83%88%EF%BC%89
- MUST

Add in-comment metadata: "詰み"

---

src/common/shogi/kakinoki.ts
src/tests/common/shogi/kakinoki.spec.ts

KIF 形式で出力する際、持ち駒がない場合に `なし` を書くように修正する。
この仕様に関するドキュメントは見当たらないが、 Kif for Windows や ShogiGUI がそのような書き方をしている。
- MUST

Fix to add "なし" to KIF

---

src/common/shogi/csa.ts
src/tests/common/shogi/csa.spec.ts

棋譜を CSA 形式で保存したときに初期局面のコメントが記録されない問題を修正。
- MUST

Fix CSA file comment

---

src/background/ipc.ts

拡張子が大文字の棋譜ファイルを開けるように修正する。
- MUST

拡張子が大文字のファイルを許容するように修正

---

src/common/i18n/locales/en.ts
src/common/i18n/locales/ja.ts
src/common/i18n/locales/zh_tw.ts
src/common/i18n/text_template.ts
src/renderer/helpers/record.ts
src/renderer/store/index.ts
src/tests/renderer/helpers/record.spec.ts

ファイル形式ごとに保存されないデータを知らせる機能

---

src/common/shogi/detect.ts
src/tests/common/shogi/detect.spec.ts

棋譜フォーマット検出において、 JKF と判断する条件を修正。
- MUST

Fix record format detection

---

src/background/environment.ts
src/tests/background/conversion.spec.ts

テストで使用する一時ディレクトリの命名を統一する改善。
- MUST

update temp path for testing

---

src/background/index.ts
src/background/log.ts
src/background/settings.ts

アプリ設定のファイル I/O が Sync 関数と Async 関数 で競合してしまい、読み取ったデータが 0 バイトになることがある。
具体的には起動直後にエンジン追加をしようとすると、ファイル選択ダイアログを閉じたときの書き込みと、 Logger を初期化するための読み込みが衝突する。
readFileSync を使うのは起動直後だけにして、値をキャッシュしておくように修正する。
- MUST

Fix app setting file I/O confliction

---

src/renderer/view/tab/EngineAnalyticsElement.vue

#631 
思考タブや読み筋タブで、評価値がちょうど 0 の場合に "0" ではなく空欄になっていた問題を修正。
- MUST

思考タブや読み筋タブの評価値の表示を修正

---

src/renderer/store/game.ts

#627
棋譜の自動保存が実行された直後にエンジンから送られた評価値が反映されて、棋譜が未保存ステータスになる問題を修正する。
- MUST

棋譜の自動保存後に評価値の更新が入ってしまう問題の修正

---

package-lock.json

libwebp で OOB の脆弱性が報告されているので一応バージョンを上げておく。
ただ、 Electron 将棋の場合にこの脆弱性が問題になることは無いと思われる。
- MUST

脆弱性報告に伴うライブラリのパッチアップデート

---

src/renderer/store/record.ts

#637 
検討機能を使用すると、棋譜が保存済みであっても未保存ラベルが表示されていた。
検討の評価値は棋譜ファイルに書き出す情報に含めないのだが、エンジンから評価値を受け取ったときに未保存ステータスにするように実装されていた。
- MUST

検討機能を利用するだけで未保存ラベルが表示される問題を修正

---

src/renderer/view/dialog/PositionImageExportDialog.vue
src/renderer/view/main/BoardPane.vue
src/renderer/view/primitive/BoardLayout.ts
src/renderer/view/primitive/BoardView.vue

対局以外では常に残り時間の欄に `0:00:00` と表示されていて、情報としての意味はない。
特に局面図書き出すときや画面キャプチャをとる場合に邪魔なので、対局中以外は欄自体を表示しないようにする。
- MUST

hide clock when not playing game

---

src/background/history.ts

新しいバックアップファイルを作った際に、最大数を超えて古いファイルを消す処理が実行されていなかった。
古い履歴の削除は `trancate` 関数に一任するようにしたが、開発中の古いコード片が残っていてファイルの実態を消す前に履歴から消えていた。
- MUST

古いバックアップファイルが削除されずに残る不具合を修正

---

package.json
src/common/settings/usi.ts
src/renderer/view/dialog/AnalysisDialog.vue
src/renderer/view/dialog/CSAGameDialog.vue
src/renderer/view/dialog/GameDialog.vue
src/renderer/view/dialog/MateSearchDialog.vue
src/renderer/view/dialog/PlayerSelector.vue
src/renderer/view/dialog/ResearchDialog.vue
src/tests/common/settings/usi.spec.ts

エンジンのラベル付け（用途選択）機能に関連する以下の不具合を修正する。
- 「エンジン管理」以外の「対局」や「検討」「解析」「詰み探索」のダイアログ上からエンジンオプションを保存すると、そのダイアログで表示されていなかったエンジンが登録解除される。
- エンジンオプションを保存するとラベルが初期化される（全てチェックした状態に戻る）。こちらはどの画面を経由した場合も起こる。
- MUST

ラベル機能に伴うエンジン管理の不具合を修正

---

src/background/history.ts
src/background/image/cache.ts
src/background/menu.ts
src/common/i18n/locales/en.ts
src/common/i18n/locales/ja.ts
src/common/i18n/locales/zh_tw.ts
src/common/i18n/text_template.ts

デバッグメニューに「キャッシュのフォルダを開く」と「バックアップのフォルダを開く」を追加。
- MUST

Add sub items into debug menu

---

src/renderer/store/record.ts
src/tests/renderer/store/record.spec.ts

#560 
Floodgate スタイルの読み筋コメントに対応し、再現ダイアログで閲覧できるようにする。
- MUST

Floodgate スタイルの読み筋コメントをプレビューする機能

---

.eslintrc.cjs
scripts/publish-release.ts
src/background/log.ts
src/renderer/ipc/web.ts

#666 
eslint の no-console ルールをエラーレベルに設定する。
- MUST

Set no-console rule as error

---

src/background/args.ts
src/background/extensions.ts
src/background/index.ts
src/background/ipc.ts
src/common/file.ts
src/common/ipc/channel.ts
src/renderer/index.ts
src/renderer/ipc/api.ts
src/renderer/ipc/preload.ts
src/renderer/ipc/web.ts
src/renderer/store/index.ts
src/tests/background/args.spec.ts

#672 
起動時引数のサポートを強化する。
- 知らないオプションを無視する。
- 棋譜を読み込んだ後に指定された手数へジャンプする。
- MUST

起動時引数のサポートを強化

---

src/renderer/players/usi.ts
src/tests/renderer/players/usi.spec.ts

#686 
bestmove コマンドの予想手 (ponder) でエンジンが反則手を送ってきた事例がある。
具体的には 1 手で自分が詰ましたことで相手の合法手が全く存在しない場合に発生した。
エンジンの多くは王手放置の手も列挙した上で、王様が取られたら負け、という判定をしている。
そのためエンジン側で予想手をチェックする仕組みを作っていないと、反則手が送られてしまう。
加えてその事例では go ponder で Ponder を開始したときにエンジンがクラッシュした。
GUI からするとエンジンが自己申告したものを本人に送り返しているだけではあるのだが、
合法手チェックをしてあげた方が親切ではあるし、比較的簡単な実装なので加えておく。
この実装によって、予想手が合法手でない場合は先読みを実行しなくなる。
- MUST

予想手が合法手かどうかを検証する機能

---

src/background/window/menu.ts
src/renderer/view/dialog/PVPreviewDialog.vue
src/renderer/view/main/BoardPane.vue

#694 
Mac版アプリにおいて、テキスト入力エリア内で以下の操作ができない問題を修正する。
- コピー (Copy) - Cmd+C
- 貼り付け (Paste) - Cmd+V
- 切り取り (Cut) - Cmd+X
- 全選択 (Select All) - Cmd+A
- 元に戻す (Undo) - Cmd+Z
- 進める (Redo) - Cmd+Shift+Z
Macアプリでは、これらの操作に該当する role をメニューバーに作っておかないと、操作がレンダラーに反映されないようです。
そのため、 Mac版のみ「編集」メニューにこれら 6 つの項目を加えます。
- MUST

Macアプリでテキスト操作のショートカットキーが効かない問題を修正

---

src/background/version/check.ts
src/background/window/ipc.ts
src/common/i18n/locales/en.ts
src/common/i18n/locales/ja.ts
src/common/i18n/locales/zh_tw.ts
src/common/i18n/text_template.ts
src/common/ipc/channel.ts
src/renderer/ipc/api.ts
src/renderer/ipc/preload.ts
src/renderer/ipc/web.ts
src/renderer/view/dialog/AppSettingDialog.vue

アプリ設定ダイアログにアプリバージョンと通知に関する項目を表示する。
設定項目というわけでもないが、他に適当な設置場所がないのでとりあえずアプリ設定の中に置いてしまう。
- MUST

Add app version section info AppSettingDialog

---

src/background/index.ts

初期に vue-cli で作った時のカスタムスキーマ `app` に関するコードが残っていたので除去する。
現在は `http` か `file` のどちらかしか使っていない。
- MUST

Remove unused custom scheme privilege

---

src/renderer/view/tab/RecordComment.vue

#693 
コメントタブを表示したときにコメントのテキストエリアのみで `stopPropagation` を呼び出していたため、しおり入力欄のイベントが親要素に拾われてコピー・ペーストができない状態だった。
ルート要素に対して `stopPropagation` を実行するように修正する。
- MUST

Fix to stop event propagation from bookmark text input

---

vite.config.mts

Vitest のバージョンを上げたタイミングから急激にカバレッジが下がっている。
どうやらスクリプトやプラグインを含めたすべてのファイルが対象になっているらしく、 exclude オプションで除外するよう修正する。
- MUST

Add coverage.exclude option

---

src/background/csa/client.ts
src/background/csa/socket.ts
src/common/i18n/locales/en.ts
src/common/i18n/locales/ja.ts
src/common/i18n/locales/zh_tw.ts
src/common/i18n/text_template.ts
src/common/settings/csa.ts
src/renderer/view/dialog/CSAGameDialog.vue
src/tests/common/settings/csa.spec.ts
src/tests/mock/csa.ts

CSA プロトコルに Keepalive と空行送信に関する設定を追加

---

src/background/csa/client.ts
src/background/window/menu.ts
src/common/control/menu.ts
src/common/control/state.ts
src/common/i18n/locales/en.ts
src/common/i18n/locales/ja.ts
src/common/i18n/locales/zh_tw.ts
src/common/i18n/text_template.ts
src/common/settings/csa.ts
src/renderer/App.vue
src/renderer/ipc/setup.ts
src/renderer/store/index.ts
src/renderer/view/dialog/AnalysisDialog.vue
src/renderer/view/dialog/CSAGameDialog.vue
src/renderer/view/dialog/ConnectToCSAServerDialog.vue
src/renderer/view/dialog/LaunchUSIEngineDialog.vue
src/renderer/view/dialog/PlayerSelector.vue

対局や検討などの機能から USI や CSA のセッションを作るのではなく、セッションの確立だけを行ってプロンプトからマニュアルでコマンド実行する機能を追加する。
後から対局や検討に使用することはできず、あくまでも管理やテストの目的で使用するためのもの。
例えば shogi-server に接続して BUOY の設定をする際に利用する。
関連: #679 
- MUST

USI や CSA プロトコルにおいてマニュアル操作目的で接続する機能

---

src/renderer/view/menu/FileMenu.vue
src/renderer/view/menu/GameMenu.vue
src/renderer/view/menu/InitialPositionMenu.vue

#732 
メニュー表示中に Escape キーを押すと、ダイアログが閉じられずになぜか親の DOM にキーイベントが行ってしまうので、 google/hotkey で Escape を拾う形で対処する。
- MUST

Fix hotkey action

---

src/renderer/store/usi.ts
src/tests/renderer/store/index.spec.ts

#175
PV において、USI 形式でないかあるいは合法手ではない文字列が来た場合に、文字列をそのまま表示する。
- MUST

Update to display irregular pv text

---

src/background/csa/client.ts
src/background/csa/index.ts
src/background/usi/engine.ts
src/background/usi/index.ts
src/common/advanced/command.ts
src/common/advanced/prompt.ts
src/renderer/ipc/api.ts
src/renderer/prompt/store.ts
src/renderer/view/prompt/CommandHistory.vue
src/tests/common/advanced/command.spec.ts
src/tests/renderer/prompt/store.spec.ts

大量のコマンドが流れるとプロンプトウィンドウのパフォーマンスが著しく悪化するため、一定時間内のコマンドをバッファリングしてまとめて描画する。
また、タイムスタンプを描画時にフォーマットするのではなく、表示用の文字列と Unix Time の両方を事前に持っておくようにする。
- MUST

Add buffering to enhance prompt performance

---

package.json
src/tests/common/helpers/datetime.spec.ts

Windows では環境変数 `TZ` を使用できないので、タイムゾーンに依存しないようにテストを修正する。 
- MUST

Fix test for windows

---

src/renderer/store/index.ts
src/renderer/store/record.ts
src/renderer/view/tab/EvaluationChart.vue

#748 
EvaluationChart.vue の更新負荷の問題を軽減します。
1. RecordManager から以下の 3 つのイベントを新たに取得できるようにして棋譜に対して watch 関数による監視をしないよう修正します。
- resetRecord - 棋譜の初期化
- updateCustomData - カスタムデータ（評価値）の更新
- updateFollowingMoves - 後続の指し手の更新（読み筋を棋譜に挿入したとき）
2. AppSettings 全体を watch 関数で監視するのをやめて、 Chart に必要なフィールドの変更だけをハンドリングします。
- MUST

評価値グラフの更新が重い問題を軽減

---

src/renderer/view/primitive/RecordView.vue

Closes #767 
消費時間にコメントが重なっていた問題を修正しました。
動作確認は Linux (Ubuntu22.04 WSL2) 環境でのみ行っています。
- MUST

fix: move-time width

---

src/command/usi-csa-bridge/index.ts

usi-csa-bridge の `--return-code` オプションのデフォルト値を OS に応じて自動的に選択します。
- MUST

Select default return code automatically

---

src/tests/background/file/history.spec.ts
src/tests/command/common/arguments.spec.ts
src/tests/renderer/store/setting.spec.ts

- テスト内の `try...catch` を `expect().toThrow()` に変更
- MUST

test: remove catch in tests

---

src/renderer/view/tab/EvaluationChart.vue

The logic for giving mates a higher priority than the score was backwards.
(cherry picked from commit b46b562efeba7ae296a419abcb99673090943c33)
See #822
- MUST

Fix the evaluation chart ignoring mates if there is a score given (v1.13)

---

src/renderer/view/tab/EngineAnalyticsElement.vue

#848 
各カラムの幅が固定だったところを、内容に合わせて幅が変化するように改修する。
- MUST

エンジンの思考情報の表示を改善
